project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: Coding Fundamentals for Humanists
  favicon: /img/dhsi_logo.png
  site-url: https://dhsi-2023.netlify.app/
  repo-url: https://github.com/ComputeCanada/dhsi_2023
  page-navigation: true
  page-footer:
    right:
      - text: About
        href: about.qmd
  navbar:
    background: light
    logo: /img/dhsi_logo.png
    logo-alt: "DHSI logo"
    title: false
    left:
      - text: Command line
        href: monday/index.qmd
      - text: Python course
        href: tuesday/index.qmd
      - text: Web scraping
        href: wednesday_scraping/index.qmd
      - text: API querying
        href: wednesday_api/index.qmd
      - text: On your own
        href: thursday/index.qmd
      - text: Presentations
        href: friday/index.qmd
  sidebar:
    - id: monday_bash
    - id: tuesday
      collapse-level: 2
      contents:
        - section:
          contents:
            - tuesday/index.qmd
        - text: <em>Python course</em>
          href: tuesday/index.qmd
        - "---"
        - section: <b><em>Afternoon session</em></b>
          href: tuesday/collections.qmd
          contents:
            - text: Collections
              href: tuesday/collections.qmd
            - text: Control flow
              href: tuesday/control_flow.qmd
            - text: Functions
              href: tuesday/functions.qmd
            - text: DataFrames with Pandas
              href: tuesday/pandas.qmd

format:
  html:
    toc: true
    toc-title: "<em>On this page:</em>"
    toc-depth: 5
    theme:
      light: [cosmo, theme.scss]
    code-overflow: wrap
    css: styles.css
    link-external-newwindow: true
    reference-location: margin
    fig-cap-location: margin

execute:
  freeze: auto
  cache: true
  error: true
  echo: true
